name: Magdalena Osak
title: GitHub - documentation and publishing 
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula



aux_links:
  "Source repository on GitHub":
    - "//https://github.com/madzka/madzka.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the homework project"